language: node_js
sudo: false
node_js:
- lts/*
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: BxhuvJtwtYvFTTj+fUAMTs20Ccb5hmXEYHbiDLDTMIe30EkRjacRFGGmFJ6FUl1Op09F9yotuWlYpKQo3wnK7RIVhPceAxiHId9ZVk+YIzsDUHkFwi3krTiFvaVBwGflbek/JesnWB+zEsF7nZ+rwMsxAW3tBr21l7MmHSzFBGaqY0RQtRgHiTugi8nq78kPtxE0S9zz1EUahcEjuMmv63P6qcVAaJhlIXwdkQNaYa0gAOWZfbfMjtrMyPyYGEDVMrN6Y+04BEXR6uu5RHsBb39GJiveAQdd/dMFJHAgJAaQ5gbSGyamwLZcMxuds7dff3JTJj0alfRaw4hKcb3heOYKCMgYwCCepWJi6UJQFteGOL9z45/dF97fxpXBH89SzUve9yTt33f0dd+cTvNXLYZo+L+DZMBwOKbdFX4zO835KiOAtrWrNAnuEqv0w39RPpAIl31mj2rEfr7JTtg/ZvhPihDGZS5uz9hlmou73EVM0vbrwsoH+JjdzauW/JGVgMSX4Xti79TBw2QKPWbACGdhxdaInGrPRmH26KU/C/ZKJTUKzJv1gQpWgDY1/spUkZNLd+kMacJDEcRTGM7oATi2j9ZlTf2KDzu+cpCpXKZGBFMmu15tIMaqh6t2X+8GGwwS3QHHKVnDjSRFDKUpAHe3aYer5BmXjPan5f9edzs=
  on:
    tags: true
    repo: flowbased/fbp-client
  skip_cleanup: true
