language: node_js
sudo: false
node_js:
- lts/*
after_success:
- "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: HA5yt/AWFOEPanCCnbYyj0BtSqTpWPVxNiVQLX2LkbLZQvgKXlgyo0v/DgI9/8RWrFUuCu0EwCc0JBtqTCCJk9Q3+ZqQMSGRNTZmy499Bx8gahkA2f0stLPXVJLfAQX5OUYQ//Cw6Nd0Z950yFVX7dKrwzJpBmheVBdRPAafGoB5cXEDy0L0Ibazf85QE9WglENM4IajIq6uhonYR8Pd4Me9nXZQmaxZmPgH64V8Nj9wOjBRmkcRnBttpsO0o90rYCvYr7R6svH3E4gMRO+hP5LG+Ri/yfJ1SQ4hotzUnYBd+He0egCywfAymHuohp+/EMMEF/CjX+hz7xYtqMke6dGVtoO/DkHTOMLxOzxvV1Hv9qTzwOtyjMW2SP5tmoUQN7C04xeV6AV2YTWjLI9ov+LZildOCb/V5uzrpRBFIiFSzXKsJ1r+jH0aM5yiUYIqoI0MXfitjfw1S68TLiKTcFLrOa4nzA65LopY8/eizWP6GQdbedRUk2xkaaKYtS6MKsLO+OOY361cVXpPco3ueiynnKfxkmxbieHKG0TOiTiRGx0e1m1colRTmjeO0Kc8Dg4LP+u8RioAvgja3Im9fVzSt6DOc3+18RzRjdebOCyLlhzPf9f8ewBI9JCzg5mGO8kNFRnP5dbeursbhEwkzNmZMczpmpwVp7ENUcPnaRE=
  on:
    tags: true
    repo: flowbased/fbp-client
